### ISSUE TITLE
Workflow does not stop when lint error is raised.

### ISSUE THREAD

**Issue by atEaE** [atEaE/fuzzy-bookmarks#13]
## Task
Workflow does not stop when lint error is raised.
Change all rules to Error to make them detectable.

## Achievement standard
Change all rules to Error to make them detectable.

## Task Detail
Itemize your tasks in detail.
- [x] "@typescript-eslint/naming-convention": "error"
- [x] "@typescript-eslint/semi": "error"
- [x]  "curly": "error"
- [x] "eqeqeq": "error"
- [x]  "no-throw-literal": "error"
