### ISSUE TITLE
Version 0.3.0 release note

### ISSUE THREAD

**Issue by atEaE** [atEaE/fuzzy-bookmarks#27]
## Summary
Summary information about the release  

### [New or Update Feature]
- [x] [#14](https://github.com/atEaE/fuzzy-bookmarks/issues/14) I want to apply an alias to my bookmarks. 
- [x] [#29](https://github.com/atEaE/fuzzy-bookmarks/issues/29) Want the export function
- [x] [#33](https://github.com/atEaE/fuzzy-bookmarks/issues/33) Deleting bookmarks one by one is a hassle.

### [Bugfix]
- [ ] none

### [Documentation]
- [x] [#31](https://github.com/atEaE/fuzzy-bookmarks/issues/31) There is no badge on the README.md
- [x] [#28](https://github.com/atEaE/fuzzy-bookmarks/issues/28) want to divide the PR template into "Merge" and "Release".

## Remarks
- Estimated release date : 2020/05/05
